name: vdp_4contacts_7709
contacts:
  A: {column: 1}
  B: {column: 2}
  C: {column: 3}
  D: {column: 4}
instruments:
  current_source:
    row_hi: 3
    row_lo: 4
    instrument: M81:S1
  voltage_meter:
    row_hi: 5
    row_lo: 6
    instrument: M81:M1
states:
  I_AB_V_DC:
    type: resistance
    group: vdp_longitudinal
    current: [A, B]
    voltage: [D, C]
    reciprocal: I_DC_V_AB
    reverse_current: I_BA_V_DC
  I_BA_V_DC:
    type: resistance
    group: vdp
    current: [B, A]
    voltage: [D, C]
  I_AB_V_CD:
    type: resistance
    group: vdp
    current: [A, B]
    voltage: [C, D]
    reciprocal: I_CD_V_AB
    reverse_current: I_BA_V_CD
  I_BA_V_CD:
    type: resistance
    group: vdp
    current: [B, A]
    voltage: [C, D]
  I_BC_V_AD:
    type: resistance
    group: vdp_longitudinal_anisotropy
    current: [B, C]
    voltage: [A, D]
    reciprocal: I_AD_V_BC
    reverse_current: I_CB_V_AD
  I_CB_V_AD:
    type: resistance
    group: vdp
    current: [C, B]
    voltage: [A, D]
  I_CD_V_AB:
    type: resistance
    group: vdp
    current: [C, D]
    voltage: [A, B]
    reciprocal: I_AB_V_CD
    reverse_current: I_DC_V_AB
  I_DC_V_AB:
    type: resistance
    group: vdp_reciprocal
    current: [D, C]
    voltage: [A, B]
    reciprocal: I_AB_V_DC
  I_BC_V_DA:
    type: resistance
    group: vdp
    current: [B, C]
    voltage: [D, A]
    reciprocal: I_DA_V_BC
  I_DA_V_BC:
    type: resistance
    group: vdp
    current: [D, A]
    voltage: [B, C]
    reciprocal: I_BC_V_DA
  I_AD_V_BC:
    type: resistance
    group: vdp_anisotropy_reciprocal
    current: [A, D]
    voltage: [B, C]
    reciprocal: I_BC_V_AD
  I_AC_V_BD:
    type: hall
    group: vdp_hall
    current: [A, C]
    voltage: [B, D]
    reciprocal: I_BD_V_AC
  I_BD_V_AC:
    type: hall
    group: vdp_hall
    current: [B, D]
    voltage: [A, C]
    reciprocal: I_AC_V_BD
